# Generated by Django 5.2 on 2025-08-22 13:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion & Apparel'), ('books', 'Books & Media'), ('home', 'Home & Garden'), ('sports', 'Sports & Outdoors'), ('beauty', 'Beauty & Personal Care'), ('toys', 'Toys & Games'), ('automotive', 'Automotive'), ('health', 'Health & Wellness'), ('food', 'Food & Beverages')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords for recommendation matching')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=16)),
                ('polarity', models.FloatField(default=0.0)),
                ('subjectivity', models.FloatField(default=0.0)),
                ('emotion', models.CharField(choices=[('happy', 'Happy'), ('angry', 'Angry'), ('sad', 'Sad'), ('surprised', 'Surprised'), ('neutral', 'Neutral')], default='neutral', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='reviews.review')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='Recommendation score (0-1)')),
                ('reason', models.CharField(blank=True, help_text='Why this product was recommended', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
