# Generated by Django 5.2 on 2025-08-23 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('fashion', 'Fashion & Apparel'), ('books', 'Books & Media'), ('home', 'Home & Garden'), ('sports', 'Sports & Outdoors'), ('beauty', 'Beauty & Personal Care'), ('toys', 'Toys & Games'), ('automotive', 'Automotive'), ('health', 'Health & Wellness'), ('food', 'Food & Beverages')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
