# Generated by Django 5.2 on 2025-08-26 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_category_review_score_review_sentiment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='product',
            new_name='item',
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('user', 'item')},
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='reason',
            field=models.CharField(blank=True, help_text='Why this item was recommended', max_length=200),
        ),
    ]
